test commit fix

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -11,9 +11,9 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Fail if we are attempting to run on the master branch
-      if: ${{GITHUB.REF_NAME == 'master'}} && github.repository == 'MaxSMokeSkaarj/space-station-14'
-      run: exit 1
+    #- name: Fail if we are attempting to run on the master branch
+      #if: ${{GITHUB.REF_NAME == 'master'}} && github.repository == 'MaxSMokeSkaarj/space-station-14'
+      #run: exit 1
 
     - name: Install dependencies
       run: sudo apt-get install -y python3-paramiko python3-lxml
